### ISSUE TITLE
[ISSUE] Unable to unlock device by fingerprint

### ISSUE THREAD

**Issue by xerta555** [Magisk-Modules-Repo/foxy-boot#1]
Hello,

I have an issue from now several weeks with this MOD.
When it's enabled, my phone (lg h870 (g6) arm64) with RR custom Nougat ROM, stock RR kernel and last Magisk Canary boot normaly with all the kernel ring buffer.

When the boot complete, admit that i let my device going in sleep mode (so i don't unlock it with my finger), the unlocking method by fingreprint don't works anymore.
I have to press the unlock button and use the fingerprint to unlock my device.

Maybe that a loggcat could help you to check if something is wrong ?

**Comment by kitsunyan** [comment]
Are you sure it's anyhow related to foxy boot? Have you tried to disable it or install previous versions (available on my github)?

**Comment by xerta555** [comment]
> Are you sure it's anyhow related to foxy boot? Have you tried to disable it or install previous versions (available on my github)?

Yeah i have test with previous versions, same issue.
When i disable the module, the fingerprint unlock feature works again without having to press a volume key or the lock key.

**Comment by kitsunyan** [comment]
I stil quite don't understand. You aren't able to unlock the screen with fpr after reboot, or you can't do it anymore until you disable the module and reboot?

Anyway, I don't know how this feature works since I don't know how Android works at all. If you want to check logcat output, check it yourself, I doubt I'll able to find anything useful there.

**Comment by kitsunyan** [comment]
Also, it would be better to create issues here https://github.com/kitsunyan/foxy-boot/issues, this repo is for module distribution only. I left issues feature enabled in this repo so Magisk bot could leave notification messages here as it was when new installer format was enforced.

**Comment by xerta555** [comment]
> I stil quite don't understand. You aren't able to unlock the screen with fpr after reboot, or you can't do it anymore until you disable the module and reboot?

I am not able to unlock the screen with fpr after reboot.

I thought you would have an idea since logically you should basically know how binary works since you have the sources, whatever the architecture on which it is executed, we might have had an idea or a lead to solve my problem.

I'll manage.

**Comment by kitsunyan** [comment]
Of course I know how the binary works, but I don't know how it can affect fingerprint reader and keyguard screen. Tbh it seems strange to me that you're trying to use fpr after reboot since you should be forced to use pin code or something else after reboot.

**Comment by xerta555** [comment]
@kitsunyan Not wrong, bcz i enabled an option in my RR custom ROM to directly unlock the device by fingerprint. So it could make side effect on my device.

The thing who's strange for me, it's that the fingerprint method don't works just after the reboot, but it works if i wakeup the device screen after a reboot, unlock it manualy and unlock by fingerprint sensor.

**Comment by xerta555** [comment]
@kitsunyan Hello, after having update your module to 1.4, apparently for no reason, i don't get this bug again.
